name: Test

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Show
        run: ls -lR .
      - name: Run a one-line script
        run: echo "`date +%s`" > result_job1.log
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: result_job1
          path: result_job1.log
      - name: Show
        run: ls -lR .
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Show
        run: ls -lR .
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo "`date +%s`" > result1.log
      - name: Run a one-line script
        run: echo "`date +%s`" > result2.log

      - name: Download Previous Reports
        continue-on-error: true
        run: |
          bash download.sh
          unzip reports.zip -d old_reports
      - name: Show
        run: ls -lR .
      - name: Download job1 Reports
        continue-on-error: true
        uses: actions/download-artifact@v2
        with:
          name: result_job1
      - name: Show
        run: ls -lR .
      - name: Save Reports
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: result*.log
          retention-days: 1
      - name: Show
        run: ls -lR .
