name: TestContainer

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    container:
        image: ubuntu:latest
    defaults:
        run:
            working-directory: job1
    steps:
      - name: Show
        run: ls -lR .
      - name: Run a one-line script
        run: echo "`date +%s`" > result_job1.log
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: result_job1
          path: result_job1.log
      - name: Show
        run: ls -lR .
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Show
        run: ls -lR .
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo "`date +%s`" > result_job2_1.log
      - name: Run a one-line script
        run: echo "`date +%s`" > result_job2_2.log

      - name: Download Previous Reports
        continue-on-error: true
        run: |
          python3 download.py reports 6c566b5b6d3dce17e0e6511892ea246a20fc69e5
          unzip reports.zip -d old_reports
      - name: Show
        run: ls -lR .
      - name: Download job1 Reports
        continue-on-error: true
        uses: actions/download-artifact@v2
        with:
          name: result_job1
      - name: Show
        run: ls -lR .
      - name: Save Reports
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: result_job2*.log
          retention-days: 1
      - name: Show
        run: ls -lR .
