
   
# Test
name: Event

on:
  # Manual trigger for testing.
  workflow_dispatch:
    inputs:
      mode:
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Event
        run: |
         echo "event_name==push? ${{ github.event_name == 'push' }}"
