name: TestSymbolicInContainer

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    container:
        image: ubuntu:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Symbolic link
        run: |
          ln -s /bin .
          ls -lR .
      - name: Add something
        run: echo "`date +%s`" > ./bin/result_job1.log
      - name: Show
        run: ls -lR ./bin
