name: TestSymbolicInContainer

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    container:
        image: ubuntu:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y -q --no-install-recommends \
                  make cmake wget unzip libtinfo-dev libz-dev libcurl4-openssl-dev g++ sudo
      - name: Symbolic link
        run: |
          ln -s /tmp .
          ls -lR .
      - name: Checkout ccache
        uses: actions/checkout@v2
        with:
          path: ./tmp
          repository: ccache/ccache
      - name: Build ccache
        run: |
          ls -lR .
          cd ./tmp
          pwd
          mkdir build; cd build
          cmake -DZSTD_FROM_INTERNET=ON -DCMAKE_BUILD_TYPE=Release ..
          make -j; make install
      - name: Show
        run: |
          which ccache
          ccache --help
