
   
# Test
name: Event

on:
  # Manual trigger for testing.
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Event
        run: |
         echo "${{ github.event_name }}"
         echo "event_name==workflow_dispatch? ${{ github.event_name == 'workflow_dispatch' }}"
         if [ ${{ github.event_name == 'workflow_dispatch' }} == "true" ]; then
           echo "Matched true"
         fi
