
   
# Test
name: Test

on:
  # Manual trigger for testing.
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "job1"
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "job2"
  job3:
    runs-on: ubuntu-latest
    steps:
      - run: echo "job3"
  final:
    needs: [job1, job2, job3]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          if [[ "${{ needs.job1.result}}" == "success" &&
                "${{ needs.job2.result}}" == "success" &&
                "${{ needs.job3.result}}" == "success" ]]; then
            echo "All success"
          else
            echo "One or more failed"
          fi
          echo "finalized"
